version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 7022:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mizz@mizz.com
      - PGADMIN_DEFAULT_PASSWORD=mizz
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
